export const dashboardTheme = {
  background: '#F6FAF4',
  surface: '#F9F9FF',
  surfaceLowest: '#FFFFFF',
  surfaceLow: '#EAF7EF',
  surfaceContainerLow: '#F1F3FF',
  surfaceVariant: '#DCE2F7',
  surfaceContainer: '#E9EDFF',
  surfaceBright: '#F9F9FF',
  surfaceContainerHighest: '#DCE2F7',
  primary: '#005129',
  primaryContainer: '#0B6B3A',
  primaryFixedDim: '#84D99C',
  primaryFixed: '#9FF5B7',
  onPrimaryFixedVariant: '#00522A',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#93E9AB',
  surfaceContainerHigh: '#E1E8FD',
  onSurface: '#141B2B',
  onBackground: '#141B2B',
  onSurfaceVariant: '#3F4940',
  textMuted: '#6B7280',
  headingGreen: '#064D2E',
  outline: '#6F7A70',
  outlineVariant: '#E5E7EB',
  successGreen: '#0B6B3A',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  secondary: '#2C6A48',
  secondaryContainer: '#ADEEC3',
  onSecondaryContainer: '#306E4C',
  tertiary: '#695F00',
  tertiaryContainer: '#BCAD32',
  creditsAccent: '#CA8A04',
  creditsSurface: '#FEFCE8',
  marginMobile: 16,
  headerHeight: 56,
  tabBarHeight: 88,
} as const;

export const dashboardShadow = {
  shadowColor: '#0B6B3A',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.04,
  shadowRadius: 12,
  elevation: 3,
};

export const dashboardShadowUp = {
  shadowColor: '#10251A',
  shadowOffset: { width: 0, height: -4 },
  shadowOpacity: 0.05,
  shadowRadius: 20,
  elevation: 8,
};
