export const officerTheme = {
  background: '#F6FAF4',
  surface: '#F9F9FF',
  surfaceLowest: '#FFFFFF',
  surfaceLow: '#F1F3FF',
  surfaceContainer: '#E9EDFF',
  surfaceContainerHigh: '#E1E8FD',
  surfaceVariant: '#DCE2F7',
  primary: '#0B6B3A',
  primaryContainer: '#0B6B3A',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#93E9AB',
  secondary: '#2C6A48',
  secondaryContainer: '#ADEEC3',
  secondaryFixed: '#B0F1C6',
  onSecondaryContainer: '#306E4C',
  onSecondaryFixedVariant: '#0D5132',
  onSurface: '#141B2B',
  onSurfaceVariant: '#3F4940',
  outline: '#6F7A70',
  outlineVariant: '#BFC9BE',
  tertiary: '#695F00',
  tertiaryContainer: '#BCAD32',
  onTertiaryFixedVariant: '#4F4700',
  successGreen: '#2C6A48',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  headingGreen: '#005129',
  marginMobile: 16,
  headerHeight: 64,
  tabBarHeight: 64,
} as const;

export const officerShadow = {
  shadowColor: 'rgba(11, 107, 58, 0.12)',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.12,
  shadowRadius: 12,
  elevation: 4,
};

export const officerCardShadow = {
  shadowColor: 'rgba(11, 107, 58, 0.04)',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 1,
  shadowRadius: 12,
  elevation: 2,
};
