import type { FarmerReportItem } from './farmerReportHelpers';

export function sanitizePdfFileName(title: string): string {
  const safe = title
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');

  return `${safe || 'bhuguard-report'}.pdf`;
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;

    if (next.length > maxChars) {
      if (current) {
        lines.push(current);
      }

      current = word.length > maxChars ? `${word.slice(0, maxChars - 1)}…` : word;
    } else {
      current = next;
    }
  }

  if (current) {
    lines.push(current);
  }

  return lines.length > 0 ? lines : ['—'];
}

function buildPdfContent(lines: string[]): string {
  const commands = ['BT', '/F1 11 Tf', '48 760 Td'];

  lines.forEach((line, index) => {
    if (index > 0) {
      commands.push('0 -16 Td');
    }

    commands.push(`(${escapePdfText(line)}) Tj`);
  });

  commands.push('ET');

  return `${commands.join('\n')}\n`;
}

export function buildFarmerReportPdfBytes(report: FarmerReportItem, farmerName = 'Farmer'): Uint8Array {
  const generatedAt = new Date().toLocaleString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const bodyLines = [
    'BHUGUARD · DIGITAL MRV FOR CLIMATE ACTION',
    '',
    'Bhuguard Verification Report',
    report.title,
    `Status: ${report.statusBadge.replace(/_/g, ' ')}`,
    '',
    `Description: ${report.description}`,
    `Farmer: ${farmerName}`,
    `Report ID: ${report.id}`,
    `Source: ${report.sourceType} #${report.sourceId || 'catalog'}`,
    `Updated: ${report.updatedLabel.replace('Updated: ', '')}`,
    `Generated At: ${generatedAt}`,
    '',
    'This document is generated by Bhuguard for carbon monitoring,',
    'verification and MRV compliance.',
    `Document ID: ${report.id} · Bhuguard Confidential`,
  ].flatMap((line) => (line === '' ? [''] : wrapText(line, 78)));

  const stream = buildPdfContent(bodyLines);
  const streamLength = new TextEncoder().encode(stream).length;

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n',
    `4 0 obj\n<< /Length ${streamLength} >>\nstream\n${stream}endstream\nendobj\n`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];

  for (const object of objects) {
    offsets.push(new TextEncoder().encode(pdf).length);
    pdf += object;
  }

  const xrefOffset = new TextEncoder().encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';

  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return new TextEncoder().encode(pdf);
}
